Vagrant.configure("2") do |config|
  master = {
    name: "alagriniS",
    ip: "192.168.56.110",
    memory: 1024,
    cpus: 2,
    hostname: "razahaS",
  }

  config.vm.box = "debian/bookworm64"

  config.vm.define master[:name] do |server|
    server.vm.hostname = master[:hostname]
    server.ssh.insert_key = false
    server.vm.network "private_network", ip: master[:ip]

    # Forward SSH port (optional)
    server.vm.network "forwarded_port", guest: 4711, host: 4711

    server.vm.provider "virtualbox" do |vb|
      vb.memory = master[:memory]
      vb.cpus = master[:cpus]
      vb.name = master[:name]
    end

    server.vm.provision "file", source: "apps", destination: "/home/vagrant/apps"
    
    # Update SSH configuration, reset password, and install packages
    server.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      echo "vagrant:vagrant" | chpasswd
      systemctl restart ssh
      apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y vim curl net-tools
    SHELL

    # Install K3s
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--node-ip #{master[:ip]}" sh -
    SHELL
  end
end