Vagrant.configure("2") do |config|
	master = {
		name: "alagriniS",
	  ip: "192.168.56.110",
	  memory: 1024,
	  cpus: 1,
	  hostname: "razahaS",
	}
  
	config.vm.box = "debian/bookworm64"

  
	config.vm.define master[:name] do |server|
	  server.vm.hostname = master[:hostname]
	  server.vm.network "private_network", ip: master[:ip]

		server.vm.provision "file", source: "apps", destination: "/home/vagrant/apps"

	  server.vm.provider "virtualbox" do |vb|
		vb.memory = master[:memory]
		vb.cpus = master[:cpus]
		vb.name = master[:name]
	  end
  
	  server.vm.provision "shell", inline: "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl net-tools"
	  server.vm.provision "shell", inline: <<-SHELL
		curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--node-ip #{master[:ip]}" sh -
	  SHELL
	end
  end