Vagrant.configure("2") do |config|
	nodes = {
	  master: {
		name: "alagriniS",
		ip: "192.168.56.110",
		memory: 1024,
		cpus: 2,
		hostname: "razahaS",
	  },
	  worker: {
		name: "alagriniSW",
		ip: "192.168.56.111",
		memory: 512,
		cpus: 1,
		hostname: "razahaSW",
	  }
	}
  
	config.vm.box = "debian/bookworm64"
  
	nodes.each do |role, opts|
	  config.vm.define opts[:name] do |node|
		node.vm.hostname = opts[:hostname]
		node.vm.network "private_network", ip: opts[:ip]
		
		# Forward SSH Tunel port for proxying
		node.vm.network "forwarded_port", guest: 4711, host: 4711
  
		node.vm.provider "virtualbox" do |vb|
		  vb.memory = opts[:memory]
		  vb.cpus = opts[:cpus]
		  vb.name = opts[:name]
		end
  
		node.vm.provision "shell", inline: "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y vim curl net-tools"
		
		# Add k=kubernetes aliase in all machines
		node.vm.provision "shell", inline: <<-SHELL
				echo "alias k='kubectl'" >> /home/vagrant/.bashrc
		SHELL

		if role == :master
		  node.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--node-ip #{opts[:ip]}" sh -
			cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
		  SHELL
		else
		  node.vm.provision "shell", inline: <<-SHELL
			MASTER_IP="#{nodes[:master][:ip]}"
			TOKEN=$(cat /vagrant/node-token)
			curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--node-ip #{opts[:ip]}" K3S_TOKEN=$TOKEN K3S_URL=https://$MASTER_IP:6443 sh -
			rm -f /vagrant/node-token
		  SHELL
		end
	  end
	end
  end