Vagrant.configure("2") do |config|
	master = {
	  name: "CorectionMachine",
	  ip: "192.168.56.115",
	  memory: 1024,
	  cpus: 2,
	  hostname: "CorectionMachine",
	}
  
	config.vm.box = "debian/bookworm64"
  
	config.vm.define master[:name] do |server|
	  server.vm.hostname = master[:hostname]
	  server.ssh.insert_key = false
	  server.vm.network "private_network", ip: master[:ip]
  
	  # Forward SSH Tunel port for proxying
	  server.vm.network "forwarded_port", guest: 4711, host: 4711
  
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = master[:memory]
		vb.cpus = master[:cpus]
		vb.name = master[:name]
	  end
  
	  # Update SSH configuration, reset password, and install packages
	  server.vm.provision "shell", inline: <<-SHELL
		sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
		echo "vagrant:vagrant" | chpasswd
		systemctl restart ssh
		apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y vim curl net-tools
	  SHELL
  
		  # Add argocd.com and wil-playground.com to /etc/hosts and point to master ip
		  server.vm.provision "shell", inline: <<-SHELL
			  echo "#{master[:ip]} argocd.com wil-playground.com" >> /etc/hosts
		  SHELL

		  # excute setup.sh script
		  server.vm.provision "shell", path: "scripts/setup.sh"

		  # execute init.sh script
		  server.vm.provision "shell", path: "scripts/init.sh"

	end
  end